
// const gameScore = 300 ;

// const balance = new  Number(100)
// console.log(balance)

// console.log(balance.toString())
// console.log(typeof balance.toString())

// console.log(balance.toString().length)
// console.log(balance.toFixed(2))

// const otherNumber = 123.8996

// console.log(otherNumber.toPrecision(3))

// const thousands = 1000000

// console.log(thousands)
// console.log(thousands.toLocaleString())



/* ++++++++++++++++++++++   MATH +++++++++++++++++++++++++ */

console.log(Math)

console.log(Math.abs(-4))

// .abs ueed for convert negative value to positive.

console.log(Math.round(6.78))

// .round give me the roundoff value or max value

console.log(Math.floor(5.78))

// .floor give the min_value

console.log(Math.ceil(4.783) )

// .ceil give the min_value

console.log(Math.sqrt(25))

console.log(Math.max(3, 4, 6, 9, 10))

// give a max_value

console.log(Math.min(2, 3, 6, 8, 9 ))

// give me a min_value

console.log(Math.pow(2,5))
 
// give me a 2 ki power 5 




























